name: Example
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      - uses: getong/mariadb-action@v1.1
        with:
          collation server: "utf8mb4_0900_ai_ci"
          mysql database: "example"
          mysql user: "user"
          mysql password: "password"
      - name: Setup Fluent CI CLI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          pipeline: .
          args: |
            dry_run
            migrate --auto-approve
          working-directory: example
        env:
          DATABASE_URL: docker://maria/latest/example
          DATABASE_DEV_URL: docker://maria/latest/schema
      - name: Run Dagger Pipelines
        run: dagger run deno run -A ../src/dagger/runner.ts
        working-directory: example
        env:
          DATABASE_URL: mysql://root:pass@mysql:3306/example
